services:
  database:
    image: postgres:15-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: park
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/docker/postgres/data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    image: park:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:postgresql://database:5432/park
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge